### ISSUE TITLE
Make it possible to rename interfaces in the consumes field

### ISSUE THREAD

**Issue by bspaans** [ankyra/escape#10]
This will allow you to consume an interface multiple times under different names:

```
consumes:
- my-provider as p1
- my-provider as p2

depends:
- release_id: my-dep-latest
  consumes:
    provider: $p1.deployment

inputs:
- id: my-input
  default: $p2.outputs.my-output
```
