### ISSUE TITLE
Only define dependency's consumers on the parent if they aren't part of a consumer mapping

### ISSUE THREAD

**Issue by bspaans** [ankyra/escape#13]
The following doesn't work at the moment, because the dependency's consumers are defined on the parent and expected to be present at deployment time:

```
depends:
- my-provider
- release_id: something-latest
  consumes:
    provider: $my-provider.deployment
```
