### ISSUE TITLE
The ability to reference subdeployments

### ISSUE THREAD

**Issue by bspaans** [ankyra/escape#14]
At the moment we can only refer to root deployments and not to the deployments within them. Coming out of #13 we need a way to programmatically reference subdeployments and update the `deployment` field on Escape packages to use this. Should make this example pass:

```
depends:
- my-provider
- release_id: something-latest
  consumes:
    provider: $my-provider.deployment
```

We've implemented a syntax for referencing subdeployments (which is used in the soft-live remote state feature) which we can reuse here.
