### ISSUE TITLE
Support new script definition in Errands

### ISSUE THREAD

**Issue by bspaans** [ankyra/escape#23]
Support e.g.:

```
errands:
  my-errand:
    script:
      cmd: docker
      args:
      - clean
```

And the short form

```
errands:
  my-errand:
    script: docker clean
```

See #22.
