### ISSUE TITLE
Support EscapeScript evaluation in build, deploy, etc. fields

### ISSUE THREAD

**Issue by bspaans** [ankyra/escape#24]
In combination with the new struct from #22 this should allow you to write things like:

```
deploy: echo $this.inputs.input_var
```

and

```
deploy:
  cmd: docker
  args:
  - build
  - "-t"
  - $this.inputs.my_image
```
