### ISSUE TITLE
Mapping providers to consumers in dependencies fails if root deployment has been renamed

### ISSUE THREAD

**Issue by bspaans** [ankyra/escape#33]
```
depends:
- id: provider as p
- id: consumer
  consumes:
    provider: $p.deployment
```
deploy with `-d something-else` will fail:

Deployment 'DEFAULT_NAME:p' does not exist
