### ISSUE TITLE
Inputs are not available in pre_build and pre_deploy

### ISSUE THREAD

**Issue by eshepelyuk** [ankyra/escape#71]
Having `escape.yml`

```
name: eshepelyuk/test
version: 0.@

inputs:
  - id: my_input
    default: my_value

pre_build:
  cmd: echo
  args:
    - $this.inputs.my_input
```

when running 

    $ escape run build

the following error appears

```
Build: Running pre_build step echo $this.inputs.my_input
Build:  Error: Field 'my_input' was not found (target collection was empty)
```

The similar error happens when declaring `pre_deploy`.

When using the same script in `deploy` and `build` phases - everything is working OK
