### ISSUE TITLE
Map parent consumers to dependency consumers

### ISSUE THREAD

**Issue by bspaans** [ankyra/escape#9]
```
depends:
- release_id: my-dep-latest
  consumes:
    provider: $my-provider.deployment

consumes:
- my-provider
```

**Comment by bspaans** [comment]
Implemented in escape-v0.21.28, but fairly useless without #10:

```
consumes:
- my-provider as p1
- my-provider as p2

depends:
- release_id: my-dep-latest
  consumes:
    provider: $p1.deployment
```
